[workspace]
members = [
    "app/gatewayd",
    "app/mock-upstream",
    "app/filters/tenant-filter",
    "app/filters/auth-filter",
    "app/filters/header-filter",
    "app/filters/rate-limit-filter",
    "app/filters/observe-filter",
]
resolver = "2"

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = true
strip = true
